import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title> Lavabos FIB</title>
                <meta name="description" content="Generated by ddanor and arraymalaya"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Et donem la benvinguda als lavabos de la FIB!
                </h1>
            </main>
        </div>
    )
}